name: Pull Request Pipeline

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run linter
              run: npm run lint

    test:
        name: Test
        runs-on: ubuntu-latest
        needs: lint

        services:
            mock-registry:
                image: registry:2
                ports:
                    - 5000:5000

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # The docker build action sets the build context to be within the action directory, so our source files must be there
            - name: Prepare build context for testing
              run: |
                  cp -r ./lib ./.github/actions/integ-tests/lib
                  cp ./package.json ./.github/actions/integ-tests/package.json
                  cp ./package-lock.json ./.github/actions/integ-tests/package-lock.json
                  cp -r ./tst/ ./.github/actions/integ-tests/tst/

            - name: Run tests
              uses: ./.github/actions/integ-tests
              with:
                  registry: 'your-registry.example.com'
                  project: 'your-project'
                  image: 'your-image'
                  tags: '["latest", "v1"]'
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  insecure: true
